export default [
  {
    id: 'historical_era_annual_mean_temp',
    title: 'Historical',
    source: 'rasdaman',
    wmsLayerName: 'annual_mean_temp',
    style: 'temp_historical_era',
    default: true,
  },
  {
    id: 'midcentury_era_annual_mean_temp',
    title: 'Projected',
    source: 'rasdaman',
    wmsLayerName: 'annual_mean_temp',
    style: 'temp_midcentury_era',
  },

  {
    id: 'historical_era_january_min',
    title: 'Historical',
    source: 'rasdaman',
    wmsLayerName: 'jan_min_max_mean_temp',
    style: 'temp_historical_january_min',
  },
  {
    id: 'midcentury_era_january_min',
    title: 'Projected',
    source: 'rasdaman',
    wmsLayerName: 'jan_min_max_mean_temp',
    style: 'temp_midcentury_january_min',
  },
  {
    id: 'historical_era_january_max',
    title: 'Historical',
    source: 'rasdaman',
    wmsLayerName: 'jan_min_max_mean_temp',
    style: 'temp_historical_january_max',
  },
  {
    id: 'midcentury_era_january_max',
    title: 'Projected',
    source: 'rasdaman',
    wmsLayerName: 'jan_min_max_mean_temp',
    style: 'temp_midcentury_january_max',
  },

  {
    id: 'historical_era_july_min',
    title: 'Historical',
    source: 'rasdaman',
    wmsLayerName: 'july_min_max_mean_temp',
    style: 'temp_historical_july_min',
  },
  {
    id: 'midcentury_era_july_min',
    title: 'Projected',
    source: 'rasdaman',
    wmsLayerName: 'july_min_max_mean_temp',
    style: 'temp_midcentury_july_min',
  },
  {
    id: 'historical_era_july_max',
    title: 'Historical',
    source: 'rasdaman',
    wmsLayerName: 'july_min_max_mean_temp',
    style: 'temp_historical_july_max',
  },
  {
    id: 'midcentury_era_july_max',
    title: 'Projected',
    source: 'rasdaman',
    wmsLayerName: 'july_min_max_mean_temp',
    style: 'temp_midcentury_july_max',
  },
]
