export default [
	{
		id: "historical_annual_mean_temp",
		title: "Historical Annual Mean Temperature (1901)",
		source: "rasdaman",
		wmsLayerName: "annual_mean_temp",
		rasdamanConfiguration: {
			dim_model: 0,
			dim_scenario: 0,
			time: "1901-01-01T00:00:00.000Z",
		},
		style: "temp",
		default: true,
	},
	{
		id: "projected_annual_mean_temp",
		title: "Projected Annual Mean Temperature (2099)",
		source: "rasdaman",
		wmsLayerName: "annual_mean_temp",
		rasdamanConfiguration: {
			dim_model: 1,
			dim_scenario: 3,
			time: "2099-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "jan_min_historical",
		title: "January Minimum Temperature (Historical, 1901)",
		source: "rasdaman",
		wmsLayerName: "jan_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 2,
			dim_model: 0,
			dim_scenario: 0,
			time: "1901-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "jan_min_projected",
		title: "January Minimum Temperature (Projected, 2099)",
		source: "rasdaman",
		wmsLayerName: "jan_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 2,
			dim_model: 1,
			dim_scenario: 3,
			time: "2099-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "jan_max_historical",
		title: "January Maximum Temperature (Historical, 1901)",
		source: "rasdaman",
		wmsLayerName: "jan_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 0,
			dim_model: 0,
			dim_scenario: 0,
			time: "1901-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "jan_max_projected",
		title: "January Maximum Temperature (Projected, 2099)",
		source: "rasdaman",
		wmsLayerName: "jan_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 0,
			dim_model: 1,
			dim_scenario: 3,
			time: "2099-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "july_min_historical",
		title: "July Minimum Temperature (Historical, 1901)",
		source: "rasdaman",
		wmsLayerName: "july_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 2,
			dim_model: 0,
			dim_scenario: 0,
			time: "1901-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "july_min_projected",
		title: "July Minimum Temperature (Projected, 2099)",
		source: "rasdaman",
		wmsLayerName: "july_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 2,
			dim_model: 1,
			dim_scenario: 3,
			time: "2099-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "july_max_historical",
		title: "July Maximum Temperature (Historical, 1901)",
		source: "rasdaman",
		wmsLayerName: "july_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 0,
			dim_model: 0,
			dim_scenario: 0,
			time: "1901-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
	{
		id: "july_max_projected",
		title: "July Maximum Temperature (Projected, 2099)",
		source: "rasdaman",
		wmsLayerName: "july_min_max_mean_temp",
		rasdamanConfiguration: {
			dim_tempstat: 0,
			dim_model: 1,
			dim_scenario: 3,
			time: "2099-01-01T00:00:00.000Z",
		},
		style: "temp",
	},
];
