<template>
  <div v-if="isHydrologyPresent">
    <div class="block content is-size-5">
      <p>
        The following results include Variable Infiltration Capacity (VIC)
        hydrologic model outputs that were generated by driving the VIC model
        with downscaled climate simulation data representing CMIP5 models chosen
        to bracket a range of temperature (cooler and hotter) and precipitation
        (dryer and wetter) futures. These models have been statistically
        downscaled using the bias corrected spatial disaggregation (BCSD)
        method. The available data extent is the terrestrial area of Alaska
        excluding the Western Aleutians. The pre-selected models include
        ACCESS1-3, CanESM2, CCSM4, CSIRO-Mk3-6-0, GFDL ESM2, inmcm4, MIROC5,
        MPI-ESM-MR, and MRI CGCM3 driven by RCP 4.5 and RCP 8.5 emissions
        scenarios. VIC hydrologic model outputs include both water state (native
        units mm) and water flux (native units mm/day) variables. State
        variables include snow water equivalent (SWE), Ice water equivalent
        (IWE) and three soil moisture (SM) layers for the following depth
        intervals: surface to 0.02 m depth, 0.02 m to 0.97 m, 0.97 m to 3.0 m
        depth. Flux variables include surface runoff, actual evapotranspiration
        (evap), snow melt, and ice melt. The VIC hydrologic model input
        variables of maximum daily 2-m air temperature (tmax), minimum daily 2-m
        air temperature (tmin), and daily precipitation (pcp) from the NCAR 12
        km Alaska Near Surface Meteorology Daily Averages (1950-2099) dataset
        and the associated modeled downscaling baseline (Daymet 12 km) are
        included in this section as well. All data represent monthly summaries
        averaged by decade. Precipitation, snow melt, glacier melt, runoff, and
        evaporation are monthly sums. Minimum and maximum temperatures and all
        soil moisture values are monthly means. Ice water equivalent and snow
        water equivalent are monthly maximums. The spatial resolution (grid cell
        size) of all data is 12 by 12 km.
      </p>

      <p>
        The modeled baseline Daymet (1980&ndash;2017) dataset is a continuous,
        gridded dataset created through interpolation of point measurements
        based on assumptions about the spatial correlation of climate variables.
        Daymet provides long-term, continuous, gridded estimates of daily
        weather and climatology variables by interpolating and extrapolating
        ground-based observations through statistical modeling techniques and is
        a research product of the Environmental Sciences Division at Oak Ridge
        National Laboratory. In this use case the 1 km x 1 km spatial resolution
        Daymet dataset (version 3) was aggregated to 12 km resolution for the
        purposes of downscaling climate models from their coarser native
        resolutions.
      </p>
    </div>

    <div class="block">
      <h4 class="title is-5 mb-1">Data preview</h4>

      <p class="content is-size-5 mb-1">
        CSV download includes decadal monthly values for the entire time series.
        Data are provided in metric units.
      </p>
      <PreviewTable
        :csvString="results.hydrology.preview"
        sizeBlurb="~3621 rows, 16 columns, ~235kb"
      />
    </div>

    <div class="block data-outro content is-size-5 no-print">
      <h4 class="title is-5 no-print">
        Data access &amp; additional information
      </h4>

      <ul>
        <li v-if="!safeMode">
          <DownloadCsvButton
            text="Download hydrology data as CSV"
            endpoint="hydrology/point"
          />
        </li>
        <li v-if="!safeMode">
          Source datasets and metadata:
          <ul>
            <li>
              <a
                href="https://catalog.snap.uaf.edu/geonetwork/srv/eng/catalog.search#/metadata/2610188c-aa38-4f47-8987-b36ec72cdd0d"
                >Alaska VIC Hydrologic Model Output (1950-2099): Decadal
                Averages of Monthly Summaries</a
              >
            </li>
          </ul>
        </li>
        <li>
          Academic references:
          <blockquote>
            Mizukami, N., Newman, A. J., Wood, A. W., Gutmann, E. D., and
            Hamman, J. J. (2022). Boulder, CO: UCAR/NCAR/RAL. 21st Century
            Hydrologic Projections for Alaska and Hawaii;
            <a href="https://doi.org/10.5065/c3kn-2y77"
              >https://doi.org/10.5065/c3kn-2y77</a
            >
          </blockquote>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import DownloadCsvButton from '~/components/DownloadCsvButton'
import UnitWidget from '~/components/UnitWidget'
import PreviewTable from '~/components/PreviewTable'
import { safe } from '~/mixins/safe.js'

export default {
  name: 'HydrologyReport',
  mixins: [safe],
  components: {
    DownloadCsvButton,
    UnitWidget,
    PreviewTable,
  },
  data() {
    return {
      radioHydroModel: 'CanESM2',
      radioHydroScenario: 'rcp45',
    }
  },
  computed: {
    ...mapGetters({
      results: 'report/results',
      isHydrologyPresent: 'report/isHydrologyPresent',
    }),
  },
}
</script>

<style lang="scss" scoped></style>
