<template>
  <div v-if="isHydrologyPresent">
    <div class="block content is-size-5">
      <p>
        This section provides access to Variable Infiltration Capacity (VIC) hydrologic model outputs that were generated by downscaled CMIP5 historical and projected climate model output, using RCP 4.5 and RCP 8.5 emissions scenarios. Data are available as monthly summaries averaged by decade. Spatial resolution: 12&#8239km.
      </p>
    </div>

    <div class="block">
      <h4 class="title is-5 mb-1">Data preview</h4>

      <p class="content is-size-5 mb-1">
        CSV download includes decadal monthly values for the entire time series. Data
        are provided in metric units.
      </p>
      <PreviewTable
        :csvString="results.hydrology.preview"
        sizeBlurb="~3621 rows, 16 columns, ~235kb"
      />
    </div>

    <div class="block data-outro content is-size-5 no-print">
      <h4 class="title is-5 no-print">
        Data access &amp; additional information
      </h4>

      <ul>
        <li>
          <DownloadCsvButton
            text="Download hydrology data as CSV"
            endpoint="hydrology/point"
          />
        </li>
        <li>
          Source datasets and metadata:
          <ul>
            <li>
              <a
                href="https://catalog.snap.uaf.edu/geonetwork/srv/eng/catalog.search#/metadata/2610188c-aa38-4f47-8987-b36ec72cdd0d"
                >Alaska VIC Hydrologic Model Output (1950-2099): Decadal
                Averages of Monthly Summaries</a
              >
            </li>
          </ul>
        </li>
        <li>
          Academic references:
          <blockquote>
            Mizukami, N., Newman, A. J., Wood, A. W., Gutmann, E. D., and
            Hamman, J. J. (2022). Boulder, CO: UCAR/NCAR/RAL. 21st Century
            Hydrologic Projections for Alaska and Hawaii;
            <a href="https://doi.org/10.5065/c3kn-2y77"
              >https://doi.org/10.5065/c3kn-2y77</a
            >
          </blockquote>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import DownloadCsvButton from '~/components/DownloadCsvButton'
import UnitWidget from '~/components/UnitWidget'
import PreviewTable from '~/components/PreviewTable'

export default {
  name: 'HydrologyReport',
  components: {
    DownloadCsvButton,
    UnitWidget,
    PreviewTable,
  },
  data() {
    return {
      radioHydroModel: 'CanESM2',
      radioHydroScenario: 'rcp45',
    }
  },
  computed: {
    ...mapGetters({
      results: 'report/results',
      isHydrologyPresent: 'report/isHydrologyPresent',
    }),
  },
}
</script>

<style lang="scss" scoped></style>
