name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Nuxt app
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Start server in background
        run: |
          npm run start &
          sleep 30
          curl -f http://localhost:3000 || (echo "Server failed to start" && exit 1)
        env:
          CI: true
      - name: Run Playwright tests
        run: npx playwright test --reporter=github --max-failures=1
        timeout-minutes: 15
        env:
          DEBUG: pw:browser
      - name: Debug on failure
        if: failure()
        run: |
          echo "Server logs:"
          cat ~/.npm/_logs/*.log || echo "No npm logs found"
          echo "Process list:"
          ps aux | grep node || echo "No node processes found"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
